nginx:
  build: ./nginx/
  ports:
    - 80:80
  links:
    - php
  volumes_from:
    - app

php:
  build: ./php/
  expose:
    - 9000
  links:
    - mysql
  volumes_from:
    - app
  environment:
    DB_HOST: mysql
    DB_DATABASE: project
    DB_USER: project
    DB_PASSWORD: project

app:
  image: php:7.0-fpm
  volumes:
    - ./app:/var/www/html
  command: echo "Application Files"

mysql:
  image: mysql:latest
  volumes_from:
    - data
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: project
    MYSQL_USER: project
    MYSQL_PASSWORD: project

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - 8080:80
  links:
    - mysql
  environment:
    PMA_HOST: mysql

data:
  image: mysql:latest
  volumes:
    - /var/lib/mysql
  command: echo "Data Files"
